### 取得所有頁面權限資料
GET {{serverUrl}}/api/permissions?pageNumber=1&rowsPerPage=10
Content-Type: application/json
Authorization: KangDa {{token}}

### 取得頁面權限資料ById
GET {{serverUrl}}/api/permissions/{id}
Content-Type: application/json
Authorization: KangDa {{token}}

### 新增頁面權限資料
POST {{serverUrl}}/api/permissions
Content-Type: application/json
Authorization: KangDa {{token}}

{
  "name": "頁面一"
}

### 修改頁面權限資料ById
PUT {{serverUrl}}/api/permissions/{id}
Content-Type: application/json
Authorization: KangDa {{token}}

{
  "name": "頁面xxxxxxxx"
}

### 刪除頁面權限資料ById
DELETE {{serverUrl}}/api/permissions/{id}
Content-Type: application/json
Authorization: KangDa {{token}}

### 取得頁面操作資料
GET {{serverUrl}}/api/permissions/{id}/actions
Content-Type: application/json
Authorization: KangDa {{token}}

### 新增頁面操作資料
POST {{serverUrl}}/api/permissions/{permissionId/{actions}
Content-Type: application/json
Authorization: KangDa {{token}}

{
  "name": "猥瑣欲為"
}

### 新增頁面操作資料
PUT {{serverUrl}}/api/permissions/{permissionId/{actions}
Content-Type: application/json
Authorization: KangDa {{token}}

{
  "name": "為所欲為"
}

###