### 使用者查詢
GET {{serverUrl}}/api/users
Content-Type: application/json
Authorization: KangDa {{token}}

### 使用者新增
POST {{serverUrl}}/api/users
Content-Type: application/json
Authorization: KangDa {{token}}

{
  "userName":"昱銘小老弟",
  "account": "YumiLoudDid"
}

### 單一使用者
GET {{serverUrl}}/api/users/3c1c2934-cc33-47d5-a458-d46a3ff87274
Content-Type: application/json
Authorization: KangDa {{token}}

### 查詢單一使用者 By Account
GET {{serverUrl}}/api/users?account=Trula15637
Content-Type: application/json
Authorization: KangDa {{token}}

### 更新使用者個人資料
PUT {{serverUrl}}/api/users/07dd3b37-589b-4c7e-aac3-424345446f81
Content-Type: application/json
Authorization: KangDa {{token}}

{
  "account": "YumiLoudDid",
  "userName": "昱銘big弟",
  "birthday": "1999/5/26",
  "city": "Kaohsiung",
  "email": "yumi@kdinfo.com",
  "gender": "男",
  "phone": "3345678"
}

### 刪除使用者個人資料
DELETE {{serverUrl}}/api/users/1774ffed-cab2-41a4-9eac-a74ae7bfa09f
Content-Type: application/json
Authorization: KangDa {{token}}